name: Deploy Resume Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Deploy Frontend to S3
  deploy-frontend:
    name: Deploy Frontend
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Sync S3 bucket
        run: |
          aws s3 sync frontend/ s3://austin-mundy-resume.site --delete
          echo "Frontend deployed to S3"
      
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
          echo "CloudFront cache invalidated"

  # Deploy Backend Lambda
  deploy-backend:
    name: Deploy Lambda Function
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Package Lambda function
        run: |
          cd backend
          zip function.zip lambda_function.py
          echo "📦 Lambda function packaged"
      
      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name resume-visitor-counter \
            --zip-file fileb://backend/function.zip
          echo "Lambda function updated"